routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\ReviewController;
use App\Http\Controllers\Site\CartController;
use App\Http\Controllers\Site\HomeController;
use App\Http\Middleware\onlyAdmin;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index']);
Route::get('/product/{id}', [HomeController::class, 'product']);
Route::post('/add_product/{id}', [CartController::class, 'add_product']);
Route::get('/cart/remove/{id}', [CartController::class, 'remove_product']);
Route::get('/cart/cart_remove_one_product/{id}',[CartController::class,'cart_remove_one_product']);
Route::get('/cart/cart_add_one_product/{id}',[CartController::class,'cart_add_one_product']);
Route::post('/cart/update_product/{id}', [CartController::class, 'update_product']);
Route::get('/cart', [CartController::class, 'cart']);
Route::post('/cart', [ReviewController::class, 'create']);
Route::get('/goCart', [CartController::class, 'goCart']);
Route::get('/checkout', [CartController::class, 'checkout']);
// Route::post('/product_review', [ReviewController::class, 'store']);






// Route::get('/', function () {
//     return view('site.home');
// });

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

Route::prefix('/admin')->middleware(['auth', onlyAdmin::class])->group(function () {
    Route::get('/dashboard',[DashboardController::class, 'index']);
    Route::resource('/categories', CategoryController::class);
    Route::resource('/products', ProductController::class);

    Route::get('/reviews', [ReviewController::class, 'index'] );
    Route::get('/reviews/getData/{id}', [ReviewController::class, 'edit'] );
    Route::post('/reviews/update', [ReviewController::class, 'update'] );


});




require __DIR__.'/auth.php';

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    public function category()
    {
        return $this->belongsTo(Category::class , "category_id", "id");
    }

    public function images()
    {
        return $this->hasMany(Image::class , "product_id", "id");
    }

    public function selected_size()
    {
        return $this->hasOne(selected_size::class);
    }

    public function selected_colour()
    {
        return $this->hasOne(selected_color::class);
    }

    public function selected_quantity()
    {
        return $this->hasOne(selected_quantity::class);
    }
    public function reviews()
    {
        return $this->hasMany(Review::class , "product_id", "id");
    }

    public function getPriceAfterDiscountAttribute()
    {
        return $this->price - $this->discount_amount;
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\ProductRequest;
use App\Models\Category;
use App\Models\Image;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data["product_list"] = Product::get();

        //return $data;
        // $data["product_list"]= Category::get();
        return view('admin.products.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data["categories"] = Category::get();
        
        return view('admin.products.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {
        try {
            if ($request->hasFile('featured_image')) {
                $path = $request->file('featured_image')->store('product_images', 'public');
            } else {
                $path = null;
            }
            $product = new Product();
            $product->name = $request->name;
            $product->price = $request->price;
            $product->discount_amount = $request->discount_amount;
            $product->stock = $request->stock;
            $product->category_id = $request->category_id;
            $product->description = $request->description;
            $product->size=$request->size;
            $product->colour=$request->colour;
            $product->featured_image = $path;
            $product->save();

            if ($request->hasFile('images')) {
                foreach ($request->file('images') as $image) {
                    $path = $image->store('product_images', 'public');
                    $image = new Image();
                    $image->path = $path;
                    $image->product_id = $product->id;
                    $image->save();
                }
            }

            flash('Successfully Added')->success();
            return redirect('/admin/products');
        } catch (\Throwable $th) {
            flash('Something went wrong ' . $th->getMessage())->error();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $product = Product::find($id);
            foreach ($product->images as $img) {
                Storage::disk('public')->delete($img->path);
            }
            $product->images()->delete();
            Storage::disk('public')->delete($product->featured_image);
            $product->delete();
            flash('Successfully Deleted')->success();
            return redirect('/admin/products');
        } catch (\Throwable $th) {
            flash('Something Went Wrong')->error();
        }
    }

    
}

resources/views/admin/products/create.blade.php
@extends('admin.layouts.app')
@section('page_title')
<div class="row mb-2">
    <div class="col-sm-6">
        <h1>Product</h1>
    </div>
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{{ url('/admin/dashboard') }}">Dashboard</a></li>
            <li class="breadcrumb-item active">Product</li>
        </ol>
    </div>
</div>
@endsection
@section('contents')
<div class="card">

    <div class="card-header">
        <h3 class="card-title">Produtc </h3>
        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                <i class="fas fa-minus"></i>
            </button>
            {{-- <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                <i class="fas fa-times"></i>
            </button> --}}

        </div>
    </div>
    <div class="card-body">
        <div class="card-header">
            <form method="POST" action="{{ route('products.store') }}" enctype="multipart/form-data">
                @csrf
                <div class="card-body">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Product Name</label>
                        <input type="text" name="name" value="{{ old('name') }}" class="form-control"
                            placeholder="Enter Product Name">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Product Category</label>
                        <select name="category_id" class="form-control">
                            @foreach ($categories as $item)
                                <option value="{{ $item->id }}">{{ $item->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Product Price</label>
                        <input type="text" name="price" value="{{ old('price') }}" class="form-control"
                            placeholder="Enter Product Price">
                    </div>

                    <div class="form-group">
                        <label for="exampleInputEmail1">Discount Amount</label>
                        <input type="text" name="discount_amount" value="{{ old('discount_amount') }}"
                            class="form-control" placeholder="Enter Discount Amount">
                    </div>

                    <div class="form-group">
                        <label for="exampleInputEmail1">Remaining Stock</label>
                        <input type="text" name="stock" value="{{ old('stock') }}" class="form-control"
                            placeholder="Enter Stoct">
                    </div>

                    <div class="form-group">
                        <label for="exampleInputEmail1">Description</label>
                        <textarea name="description" class="form-control">{{ old('description')}}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Product Size</label>
                        <input type="text" class="form-control" name="size" id="size" value="{{ old('size') }}" placeholder="Enter product sizes">
                      </div>
          
                      <div class="form-group">
                        <label for="exampleInputEmail1">Product Colour</label>
                        <input type="text" class="form-control" name="colour" id="colour" value="{{ old('colour') }}" placeholder="Enter product colour">
                      </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Featured Image</label>
                        <input type="file" name="featured_image">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Images</label>
                        <input type="file" name="images[]" multiple>
                    </div>
                </div>

                <!-- /.card-body -->

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Create</button>
                </div>
            </form>

            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
        </div>
    </div>
    <!-- /.card-body -->
    {{-- <div class="card-footer">
    </div> --}}
    <!-- /.card-footer-->
</div>
@endsection

resources/views/admin/products/index.blade.php
@extends('admin.layouts.app')
@section('page_title')
<div class="row mb-2">
    <div class="col-sm-6">
        <h1>Product</h1>
    </div>
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{{ url('/admin/dashboard') }}">Dashboard</a></li>
            <li class="breadcrumb-item active">Product</li>
        </ol>
    </div>
</div>
@endsection
@section('contents')
<div class="card">

    <div class="card-header">
        <h3 class="card-title">Product List</h3>
        <div class="card-tools">
            {{-- <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                <i class="fas fa-times"></i>
            </button> --}}
            <a class="btn btn-success pull-right" href="{{ url('/admin/products/create') }}">Add New Product</a>

        </div>
    </div>
    <div class="card-body">
        <table class="table table-bordered">
            <tr>
                <td>Name</td>
                <td>Price</td>
                <td>Discount Amonunt</td>
                <td>Stock</td>
                <td>Catgory</td>
                <th>Sizes</th>
                <th>Colours</th>
                <td>Featured Image</td>
                <td>Images</td>
                <td>action</td>
            </tr>
            @foreach ($product_list as $item)
            <tr>
                <td>{{ $item->name }}</td>
                <td>{{ $item->price }}</td>
                <td>{{ $item->discount_amount }}</td>
                <td>{{ $item->stock }}</td>
                <td>{{ $item->category ? $item->category->name : "" }}</td>
                @php
                $size=$item->size;
                $product_size=explode(',',$size);
                @endphp
                <td>
                  @foreach ($product_size as $one_size)
                      {{ $one_size }}<br>
                  @endforeach
                </td>
                @php
                $colour=$item->colour;
                $product_colour=explode(',',$colour);
                @endphp
                <td>
                  @foreach ($product_colour as $one_colour)
                      {{ $one_colour }}<br>
                  @endforeach
                </td>
                <td>
                    <img class="img-fluid" style="width=110px;height:120px;" src="{{ asset("storage/$item->featured_image") }}">
                    
                </td>
                <td>
                    @foreach ($item->images as $item)
                    <li class="image_li">
                        <img style="width=150px;height:150px;" src="{{ asset("storage/$item->path") }}"
                        class="img-responsive_imge inline-block" alt="Responsive image" />
                    </li>
                    @endforeach
                </td>
                <td>

                    <a href="{{ url("/admin/products/$item->id/edit") }}" class="btn btn-info">Edit</a>
                    <form action="{{ url("/admin/products/$item->id") }}" method="post" style="display:inline"
                        onSubmit="return confirm('Are you sure you want to delete?')">
                        @csrf
                        @method("delete")
                        <input type="submit" class="btn btn-info" value="Delete">
                    </form>

                </td>
            </tr>
            @endforeach
        </table>
    </div>
    <!-- /.card-body -->
    <div class="card-footer">
    </div>
    <!-- /.card-footer-->
</div>
@endsection