routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\ReviewController;
use App\Http\Controllers\Site\CartController;
use App\Http\Controllers\Site\HomeController;
use App\Http\Middleware\onlyAdmin;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index']);
Route::get('/product/{id}', [HomeController::class, 'product']);
Route::post('/add_product/{id}', [CartController::class, 'add_product']);
Route::get('/cart/remove/{id}', [CartController::class, 'remove_product']);
Route::get('/cart/cart_remove_one_product/{id}',[CartController::class,'cart_remove_one_product']);
Route::get('/cart/cart_add_one_product/{id}',[CartController::class,'cart_add_one_product']);
Route::post('/cart/update_product/{id}', [CartController::class, 'update_product']);
Route::get('/cart', [CartController::class, 'cart']);
Route::post('/cart', [ReviewController::class, 'create']);
Route::get('/goCart', [CartController::class, 'goCart']);
Route::get('/checkout', [CartController::class, 'checkout']);
// Route::post('/product_review', [ReviewController::class, 'store']);






// Route::get('/', function () {
//     return view('site.home');
// });

// Route::get('/dashboard', function () {
//     return view('dashboard');
// })->middleware(['auth'])->name('dashboard');

Route::prefix('/admin')->middleware(['auth', onlyAdmin::class])->group(function () {
    Route::get('/dashboard',[DashboardController::class, 'index']);
    Route::resource('/categories', CategoryController::class);
    Route::resource('/products', ProductController::class);

    Route::get('/reviews', [ReviewController::class, 'index'] );
    Route::get('/reviews/getData/{id}', [ReviewController::class, 'edit'] );
    Route::post('/reviews/update', [ReviewController::class, 'update'] );


});




require __DIR__.'/auth.php';

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    public function products()
    {
        return $this->hasMany(Product::class , "category_id", "id");
    }
    
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Enums\MainCategory;
use App\Http\Controllers\Controller;
use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data["category_list"] = Category::get();
        return view('admin.categories.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data["main_category"] = MainCategory::asSelectArray();
        return view('admin.categories.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        $category = new Category();
        $category->name = $request->name;
        $category->main_category_id = $request->main_category_id;
        $category->save();
        flash('successfully created')->success();
        return redirect('/admin/categories');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);
        if(!$category)
        {
            flash('No data found')->error();
            return redirect('/admin/categories');
        }
        $data["category"] = $category;
        $data["main_category"] = MainCategory::asSelectArray();
        return view('admin.categories.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, $id)
    {
        $category = Category::find($id);
        if(!$category)
        {
            flash('No data found')->error();
            return redirect('/admin/categories');
        }
        $category->name = $request->name;
        $category->main_category_id = $request->main_category_id;
        $category->save();
        flash('Successfully created')->success();
        return redirect('/admin/categories');
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
        if(!$category)
        {
            flash('No data found')->error();
            return redirect('/admin/categories');
        }
        $category->delete();
        flash('Successfully Deleted')->success();
        return redirect('/admin/categories');

    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.app')
@section('page_title')
<div class="row mb-2">
    <div class="col-sm-6">
        <h1>Category</h1>
    </div>
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{{ url('/admin/dashboard') }}">Dashboard</a></li>
            <li class="breadcrumb-item active">Category</li>
        </ol>
    </div>
</div>
@endsection
@section('contents')

<div class="card">

    <div class="card-header">
        <h3 class="card-title">Category List</h3>
        <div class="card-tools">
            {{-- <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                <i class="fas fa-times"></i>
            </button> --}}

        </div>
    </div>
    <div class="card-body">
        <div class="card-header">
            <form method="POST" action="{{ route('categories.store') }}">
                @csrf
                <div class="card-body">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Main Category</label>
                        <select name="main_category_id" class="form-control">
                            <option value="">--Select a Category--</option>
                            @foreach ($main_category as $key => $item)
                            <option value="{{ $key }}" {{ old('main_category_id')==strval($key) ? 'selected' : '' }}>
                                {{ $item }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <label for="exampleInputEmail1">Catgory Name</label>
                        <input type="text" name="name" value="{{ old('name') }}" class="form-control"
                            placeholder="Enter Category Name">
                    </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Create</button>
                </div>
            </form>

            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
        </div>
    </div>
    <!-- /.card-body -->
    <div class="card-footer">
    </div>
    <!-- /.card-footer-->
</div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.app')
@section('page title')
<div class="row mb-2">
  <div class="col-sm-6">
    <h1>Category</h1>
  </div>
  <div class="col-sm-6">
    <ol class="breadcrumb float-sm-right">
      <li class="breadcrumb-item"><a href="{{ url('/admin/dashboard') }}">Dashboard</a></li>
      <li class="breadcrumb-item active">Category</li>
    </ol>
  </div>
</div>
@endsection
@section('contents')
<div class="card">
  <div class="card-header">
    <h3 class="card-title">Category List</h3>
    <div class="card-tools">
      <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
        <i class="fas fa-minus"></i>
      </button>
      {{-- <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
        <i class="fas fa-times"></i>
      </button> --}}
      <a class="btn btn-success" href="{{ url('/admin/categories/create') }}">Add New Category</a>
    </div>
  </div>
  <div class="card-body">
    <form method="POST" action="{{ url("/admin/categories/$category->id") }}">
      @csrf
      @method('put')
      <div class="card-body">
        <div class="form-group">
          <label style="background-color: aqua" for="exampleInputEmail1">Main Category</label>
          <select name="main_category_id" class="form-control">
            @foreach ($main_category as $key=>$item)
            <option style="background-color: aquamarine" value="{{$key}}" {{ $category->main_category_id==strval($key) ? 'selected' : '' }}>{{$item}}</option>
            @endforeach
          </select>
        </div>
        <div class="form-group">
          <label style="background-color: aqua" for="exampleInputEmail1">Category name</label>
          <input type="text" name="name" class="form-control" value="{{ $category->name }}" 
            placeholder="Enter Category name">
        </div>

      </div>
      <!-- /.card-body -->

      <div class="card-footer">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </form>
    @if ($errors->any())
    <div class="alert alert-danger">
      <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
      </ul>
    </div>
    @endif
  </div>
  <!-- /.card-body -->
  <div class="card-footer">

  </div>
  <!-- /.card-footer-->
</div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.app')
@section('page_title')
<div class="row mb-2">
  <div class="col-sm-6">
    <h1>Category</h1>
  </div>
  <div class="col-sm-6">
    <ol class="breadcrumb float-sm-right">
      <li class="breadcrumb-item"><a href="{{ url('/admin/dashboard') }}">Dashboard</a></li>
      <li class="breadcrumb-item active">Category</li>
    </ol>
  </div>
</div>
@endsection
@section('contents')
<!-- Default box -->
<div class="card">
  <div class="card-header">
    <h3 class="card-title">Category List</h3>

    <div class="card-tools">
      <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
        <i class="fas fa-minus"></i>
      </button>
      {{-- <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
        <i class="fas fa-times"></i>
      </button> --}}
      <a class="btn btn-success pull-right" href="{{ url('/admin/categories/create') }}">Add New Category</a>
    </div>
  </div>
  <div class="card-body">
    <table class="table table-bordered table-dark ">
      <tr>
        <td style="text-align: center">Category Name</td>
        <td style="text-align: center">Main categories</td>
        <td style="text-align: center">Action</td>
      </tr>
      @foreach ($category_list as $item)
      <tr>
        <td>{{ $item->name}}</td>
        <td>{{ App\Enums\MainCategory::getDescription($item->main_category_id) }}</td>
        <td style="text-align: center">
          <a href="{{ url("/admin/categories/$item->id/edit") }}" class="btn btn-info">Edit</a>
          {{-- <a href="{{ route('categories.edit', ['category'=>$item->id]) }}" class="btn btn-info">Edit</a> --}}
          <form action="{{ url("/admin/categories/$item->id") }}" method="post" style="display:inline"
            onSubmit="return confirm('Are you sure you want to delete?')">
            @csrf
            @method("delete")
            <input type="submit" class="btn btn-danger" value="Delete">

          </form>
        </td>
      </tr>
      @endforeach
    </table>
  </div>
  <!-- /.card-body -->
  {{-- <div class="card-footer">
    Footer
  </div> --}}
  <!-- /.card-footer-->
</div>

@endsection